server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** # 用户微服务 http://api.leyou.com/api/user/send
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务 http://api.leyou.com/api/cart/list
    order-service: /order/** # 订单微服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true
  sensitive-headers:  # 覆盖默认敏感头信息

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：10000ms

ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
ly:
  jwt:
    pubKeyPath: D:\Java\tmp\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item